FactoryBot.define do
  factory :tw_cuentum do
    name "MyString"
    screen_name "MyString"
    estado 1
    id_bot 1
    id_str "MyString"
    location "MyString"
    profile_location "MyString"
    description "MyString"
    url "MyString"
    expanded_url "MyString"
    display_url "MyString"
    protected false
    friends_count 1
    listed_count 1
    followers_count 1
    created_at_perfil "MyString"
    datetime "MyString"
    favourites_count 1
    utc_offset 1
    time_zone "MyString"
    geo_enabled false
    verified false
    statuses_count 1
    lang "MyString"
    text "MyString"
    truncated false
    geo "MyString"
    coordinates "MyString"
    place "MyString"
    contributors "MyString"
    is_quote_status false
    retweet_count 1
    favorite_count 1
    favorited false
    retweeted false
    contributors_enabled false
    is_translator false
    is_translation_enabled false
    profile_background_color "MyString"
    profile_background_image_url "MyString"
    profile_background_image_url_https "MyString"
    profile_background_tile false
    profile_image_url "MyString"
    profile_image_url_https "MyString"
    profile_banner_url "MyString"
    profile_link_color "MyString"
    profile_sidebar_border_color "MyString"
    profile_sidebar_fill_color "MyString"
    profile_text_color "MyString"
    profile_use_background_image false
    has_extended_profile false
    default_profile false
    default_profile_image false
    translator_type "MyString"
  end
end
